### ISSUE TITLE
Repeating locations

### ISSUE THREAD

**Issue by planemad** [unicef/projectconnect-app#11]
Kudos on making a great game ❤️ 

Been playing for around 15 mins and  almost all my locations seem to be repeating. It seems like i might have hit a limit on how much i can review and its not clear if i should just keep going?

![Screen Shot 2021-04-08 at 11 43 05 PM](https://user-images.githubusercontent.com/126868/114126024-97f00180-98c5-11eb-800d-9d47215fc4f9.png)

**Comment by lacabra** [comment]
hi @planemad 👋 

Thanks for your interest in this game, and for playing along. The version that you played is on a "pre-release" mode, where there is only a total of 96 locations, and two things should happen:
- You should not see repeated schools
- When you map all schools, the game will tell you and you don't be able to play anymore.

I will need to check the [code](https://github.com/lacabra/proco-map-app/blob/master/pages/api/getLocations/%5Buuid%5D.js) that chooses the schools from the DB, which should not select those that have been tagged by a given user, and revert back.

I'm curious to know how did you come across this game, since we haven't really advertised yet. Care to share? :)

Coincidentally, this weekend/early-next week we are preparing for an initial campaign with a new dataset that will contain 1000 schools, aiming for 100 users to play the game 10 times thereby mapping 100 x 10 x 10 = 10,000 locations, with which a uniform distribution would result in about 10 reviews for each location.

Do you have any suggestions for anything to improve of the user interface or user experience?

Thanks!
Victor

**Comment by lacabra** [comment]
@planemad 

I have manually played the game with a new user and tagged all schools. The code works as expected, and no school ID is ever repeated. I did notice however that there were a few duplicate locations (different school IDs that contained the same set of coordinates). This is good news because the flaw is in the data, not the code, and we will be uploading a brand new data set in the next day or two, so the issue that you have observed will go away. When the user reaches 96 locations in the current game, the user is informed that s/he has tagged all possible schools, and s/he is not allowed to play any further:

![Screen Shot 2021-04-09 at 6 48 44 PM](https://user-images.githubusercontent.com/6098973/114252990-6464b400-9965-11eb-8168-d5e96f39705b.png)

**Comment by planemad** [comment]
> I have manually played the game with a new user and tagged all schools. The code works as expected, and no school ID is ever repeated.

Tried again with my logged in github handle and these are the summaries after each set. In 40 locations looks like only 2 new ones were there.

![Screen Shot 2021-04-10 at 9 50 30 PM](https://user-images.githubusercontent.com/126868/114289646-aebe6180-9a47-11eb-8951-75fe9f76088f.png)
![Screen Shot 2021-04-10 at 9 51 23 PM](https://user-images.githubusercontent.com/126868/114289647-aebe6180-9a47-11eb-8ea2-256ecb41e89d.png)
![Screen Shot 2021-04-10 at 9 52 45 PM](https://user-images.githubusercontent.com/126868/114289648-aebe6180-9a47-11eb-9e9c-3ccc5d33e9ec.png)
![Screen Shot 2021-04-10 at 9 56 08 PM](https://user-images.githubusercontent.com/126868/114289649-af56f800-9a47-11eb-9d16-3d98d9b1745f.png)


> curious to know how did you come across this game

This was shared internally at Mapbox :)

> Do you have any suggestions for anything to improve of the user interface or user experience?

Overall, its quite great. The only thing i would ask for is:

- Keyboard shortcuts for desktop for faster review.
- Ability to correct/invalidate a decision. On a few occaisions i've made a mistake with no way of fixing it.

**Comment by lacabra** [comment]
> This was shared internally at Mapbox :)

Ah, now I understand 🙃

> Keyboard shortcuts for desktop for faster review.

Tracking it in lacabra/proco-map-app#81

> Ability to correct/invalidate a decision. On a few occasions i've made a mistake with no way of fixing it.

This one is trickier because the moment that you make a decision you are presented with the results on how your decision compares to others'. If at that time you see that your decision differs from the rest, you may be tempted to change it to match what the majority thinks, and we want each player's decision to be independent. Thus, this does not have an easy fix unless we asked for confirmation for each of the user's answers, which would significantly slow the game. We're open to suggestions, but the way the game flows currently, this is not likely to be changed.

Thanks again!

Cc: @CallaJune

**Comment by planemad** [comment]
> Thus, this does not have an easy fix unless we asked for confirmation for each of the user's answers

👍 Trying to fix this completely depends on the impact of an incorrect decision. If every location is going to get 10 reviewers, its probably not important to fix since the error would get averaged out.

**Comment by lacabra** [comment]
Thanks, given that we are tracking the specific issue that you pointed out in another repo, I am closing this one.

**Comment by lacabra** [comment]
The original issue about repeating locations is still an issue. I looked into it while not logged in, and I did not observe it; but after playing while logged in, I have observe it as well. Investigating...

**Comment by yuletide** [comment]
I have found this while playing while logged in, I have seen the same school in kazakhstan 10+ times now and we've had users report their score no longer increasing after hitting about 1100

**Comment by lacabra** [comment]
Thanks @yuletide. We are aware of this issue, which is a significant bug. I will prioritize solving this tomorrow. Stay tuned for updates and thanks for playing 🥇

**Comment by yuletide** [comment]
Sure thing, thanks for building this awesome tool and including us! Excited to be a part of this project.

**Comment by lacabra** [comment]
@yuletide and @planemad: This bug has been fixed. If you could kindly let everyone else know at Mapbox that this has been fixed, the top mappers in the group will very soon hit the max number of available schools, and will reach the end of their games 🏆

Thank you

**Comment by planemad** [comment]
🙏 @lacabra . Folks are ecstatic haha, and waiting for more locations.
